services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    pull_policy: always
    healthcheck:
      test: ollama ps || exit 1
      interval: 10s
    restart: unless-stopped
    networks:
      - aiproxy
    volumes:
      - /mnt/Pool01/Apps/ollama/data:/root/.ollama
    environment:
      - OLLAMA_HOST='0.0.0.0' # uncomment to make ollama reachable by other computers on your network
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_FLASH_ATTENTION=0
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.ollama.entrypoints=websecure
      - traefik.http.routers.ollama.rule=Host(`ollama.u-acres.com`)
      - traefik.http.routers.ollama.service=ollama
      - traefik.http.services.ollama.loadbalancer.server.port=11434
      - traefik.http.routers.ollama.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.ollama.tls.domains[0].main=ollama.u-acres.com
      - "ha.monitor=true"
      - "ha.category=automation"
      - "ha.compose-file=Docker-NonCritical/Automation/AI/ai.yml"
      - "ha.service-name=ollama"
networks:
  aiproxy:
    external: true
