services:
  forgejo-runner-noncritical:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forgejo-runner-noncritical
    restart: unless-stopped
    network_mode: host
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    environment:
      - GITEA_INSTANCE_URL=https://git.${DOMAIN_NAME}
      - GITEA_RUNNER_NAME=docker-noncritical
      - GITEA_RUNNER_LABELS=docker-noncritical

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/Runner/runner.yml"
      - "ha.service-name=forgejo-runner-noncritical"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/forgejo-runner-noncritical:/data
    
    command: >
      sh -c "
        if [ ! -f /data/.runner ]; then
          echo 'Runner not registered. Please register with:';
          echo 'docker exec -it forgejo-runner-noncritical act_runner register --instance https://git.u-acres.com --name docker-noncritical --labels docker-noncritical';
          sleep infinity;
        else
          act_runner daemon;
        fi
      "
