services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      - authnet
    volumes:
      - /srv/authelia/config:/config
      - /srv/authelia/secrets:/secrets:ro
    environment:
      - TZ=America/Chicago
      - X_AUTHELIA_CONFIG_FILTERS=template
      - DOMAIN_NAME=${DOMAIN_NAME}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=${AUTHELIA_OIDC_HMAC_SECRET}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD=${AUTHELIA_DB_PASSWORD}
      - NORISH_OIDC_CLIENT_SECRET=${NORISH_OIDC_CLIENT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.${DOMAIN_NAME}`)"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=${CERTRESOLVER:-cloudflare}"
      - "traefik.http.routers.authelia.tls.domains[0].main=authelia.${DOMAIN_NAME}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "ha.monitor=true"
      - "ha.category=auth"
      - "ha.compose-file=Docker-Critical/Auth/Authelia.yml"
      - "ha.service-name=authelia"
    depends_on:
      authelia-db:
        condition: service_healthy
      lldap:
        condition: service_started

  authelia-db:
    image: postgres:15
    container_name: authelia-db
    restart: unless-stopped
    networks:
      - authnet
    volumes:
      - /srv/authelia/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authelia
      - POSTGRES_USER=authelia
      - POSTGRES_PASSWORD=${AUTHELIA_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authelia -U authelia"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "ha.monitor=true"
      - "ha.category=auth"
      - "ha.compose-file=Docker-Critical/Auth/Authelia.yml"
      - "ha.service-name=authelia-db"

  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    hostname: lldap
    restart: unless-stopped
    networks:
      - authnet
    expose:
      - "3890"
    environment:
      - TZ=America/Chicago
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_LDAP_BASE_DN=${LDAP_BASE_DN}
      - LLDAP_DATABASE_URL=sqlite:///data/users.db?mode=rwc
    volumes:
      - /srv/authelia/lldap/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.rule=Host(`ldapadmin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.lldap.entrypoints=websecure"
      - "traefik.http.routers.lldap.tls.certresolver=${CERTRESOLVER:-cloudflare}"
      - "traefik.http.routers.lldap.tls.domains[0].main=ldapadmin.${DOMAIN_NAME}"
      - "traefik.http.routers.lldap.tls=true"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"
      - "traefik.http.routers.lldap.middlewares=authelia@docker"
      - "ha.monitor=true"
      - "ha.category=auth"
      - "ha.compose-file=Docker-Critical/Auth/Authelia.yml"
      - "ha.service-name=lldap"

networks:
  authnet:
    external: true
