services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - authnet
    environment:
      - TZ=${TZ:-America/Chicago}
      - DOMAIN=https://vault.${DOMAIN_NAME}
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - DATABASE_URL=postgresql://vaultwarden:${VAULTWARDEN_DB_PASSWORD}@vaultwarden-db:5432/vaultwarden
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - LOG_LEVEL=warn
    volumes:
      - /srv/vaultwarden/data:/data
    depends_on:
      vaultwarden-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=authnet
      # Web UI
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`vault.${DOMAIN_NAME}`)
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.vaultwarden.tls.domains[0].main=vault.${DOMAIN_NAME}
      # WebSocket for live sync
      - traefik.http.routers.vaultwarden-ws.entrypoints=websecure
      - traefik.http.routers.vaultwarden-ws.rule=Host(`vault.${DOMAIN_NAME}`) && Path(`/notifications/hub`)
      - traefik.http.routers.vaultwarden-ws.service=vaultwarden-ws
      - traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012
      - traefik.http.routers.vaultwarden-ws.tls.certresolver=${CERTRESOLVER:-cloudflare}
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=auth
      - ha.compose-file=Docker-Critical/Auth/vaultwarden.yml
      - ha.service-name=vaultwarden

  vaultwarden-db:
    image: postgres:15
    container_name: vaultwarden-db
    restart: unless-stopped
    networks:
      - authnet
    environment:
      - POSTGRES_DB=vaultwarden
      - POSTGRES_USER=vaultwarden
      - POSTGRES_PASSWORD=${VAULTWARDEN_DB_PASSWORD}
    volumes:
      - /srv/vaultwarden/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d vaultwarden -U vaultwarden"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - ha.monitor=true
      - ha.category=auth
      - ha.compose-file=Docker-Critical/Auth/vaultwarden.yml
      - ha.service-name=vaultwarden-db
      - com.centurylinklabs.watchtower.enable=true

networks:
  authnet:
    external: true
