services:
  forgejo-runner:
    image: gitea/act_runner:latest
    container_name: forgejo-runner
    restart: unless-stopped
    user: root

    # Resource limits for gaming performance
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.2'

    labels:
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=tools
      - ha.compose-file=Docker-Desktop1/Core/Runner/runner.yml
      - ha.service-name=forgejo-runner

    volumes:
      # Docker socket for running containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Runner data persistence
      - runner_data:/data
      # Config
      - ./config.yaml:/config.yaml

    working_dir: /data

    # Install Node.js and run daemon
    entrypoint: |
      sh -c "
        apk add --no-cache nodejs npm curl &&
        act_runner daemon --config /config.yaml
      "

volumes:
  runner_data:
    name: forgejo_runner_data
