services:
  forgejo-runner:
    image: gitea/act_runner:latest
    container_name: forgejo-runner
    restart: unless-stopped
    user: root

    volumes:
      # Docker socket for running containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Runner data persistence
      - runner_data:/data
      # Config
      - ./config.yaml:/config.yaml

    working_dir: /data

    # Install Node.js and run daemon
    entrypoint: |
      sh -c "
        apk add --no-cache nodejs npm curl docker-cli-compose &&
        act_runner daemon --config /config.yaml
      "

volumes:
  runner_data:
    name: forgejo_runner_data
