name: Apply Updates - Docker Critical

on:
  workflow_dispatch:
    inputs:
      containers:
        description: 'Containers to update (comma-separated, or "all" for all with updates)'
        required: false
        default: 'all'

jobs:
  apply-updates:
    runs-on: docker-critical

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull and recreate containers
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CERTRESOLVER: ${{ vars.CERTRESOLVER }}
          TZ: ${{ vars.TZ }}
          HOMEASSISTANT_MARIADB_ROOT_PASSWORD: ${{ secrets.HOMEASSISTANT_MARIADB_ROOT_PASSWORD }}
          HOMEASSISTANT_MARIADB_PASSWORD: ${{ secrets.HOMEASSISTANT_MARIADB_PASSWORD }}
          CLOUDFLARE_EMAIL: ${{ vars.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_DNS_API_TOKEN: ${{ secrets.CLOUDFLARE_DNS_API_TOKEN }}
          CLOUDFLARE_ZONE_API_TOKEN: ${{ secrets.CLOUDFLARE_ZONE_API_TOKEN }}
          LETS_ENCRYPT_EMAIL: ${{ vars.LETS_ENCRYPT_EMAIL }}
          CONTAINERS: ${{ github.event.inputs.containers }}
        run: |
          # Map containers to their compose files and service names
          declare -A COMPOSE_MAP
          declare -A SERVICE_MAP

          COMPOSE_MAP["homeassistant"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["homeassistant"]="homeassistant"

          COMPOSE_MAP["music-assistant"]="Docker-Critical/Home/MusicAssistant/musicassistant.yml"
          SERVICE_MAP["music-assistant"]="music-assistant"

          COMPOSE_MAP["esphome"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["esphome"]="esphome"

          COMPOSE_MAP["matter-server"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["matter-server"]="matter-server"

          COMPOSE_MAP["homeassistant-db"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["homeassistant-db"]="mariadb"

          COMPOSE_MAP["homeassistant-mqtt"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["homeassistant-mqtt"]="mosquitto"

          COMPOSE_MAP["traefik"]="Docker-Critical/Networking/Proxy/proxy.yml"
          SERVICE_MAP["traefik"]="traefik"

          COMPOSE_MAP["authelia"]="Docker-Critical/Auth/Authelia.yml"
          SERVICE_MAP["authelia"]="authelia"

          COMPOSE_MAP["authelia-db"]="Docker-Critical/Auth/Authelia.yml"
          SERVICE_MAP["authelia-db"]="authelia-db"

          COMPOSE_MAP["lldap"]="Docker-Critical/Auth/Authelia.yml"
          SERVICE_MAP["lldap"]="lldap"

          COMPOSE_MAP["omada-controller"]="Docker-Critical/Networking/Omada/omada.yml"
          SERVICE_MAP["omada-controller"]="omada-controller"

          COMPOSE_MAP["avahi"]="Docker-Critical/Home/HomeAssistant/homeassistant.yml"
          SERVICE_MAP["avahi"]="avahi"

          COMPOSE_MAP["rtl_433"]="Docker-Critical/Home/RTL-SDR/rtl-sdr.yml"
          SERVICE_MAP["rtl_433"]="rtl_433"

          updated=""

          if [ "$CONTAINERS" = "all" ]; then
            # Check all and update those with available updates
            chmod +x ./scripts/check-docker-updates.sh
            CONTAINERS=""
            for container in "${!COMPOSE_MAP[@]}"; do
              if docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
                result=$(./scripts/check-docker-updates.sh "$container")
                echo "Checking $container: $result"
                if [ "$result" != "[]" ] && [ -n "$result" ]; then
                  if [ -z "$CONTAINERS" ]; then
                    CONTAINERS="$container"
                  else
                    CONTAINERS="${CONTAINERS},${container}"
                  fi
                fi
              fi
            done
            echo "Containers to update: $CONTAINERS"
          fi

          if [ -z "$CONTAINERS" ]; then
            echo "No containers need updating"
            exit 0
          fi

          # Update each container
          IFS=',' read -ra CONTAINER_LIST <<< "$CONTAINERS"
          for container in "${CONTAINER_LIST[@]}"; do
            container=$(echo "$container" | xargs)  # trim whitespace
            compose_file="${COMPOSE_MAP[$container]}"
            service_name="${SERVICE_MAP[$container]}"

            if [ -n "$compose_file" ] && [ -f "$compose_file" ]; then
              echo "Updating container $container (service: $service_name) using $compose_file"

              # Pull new image
              image=$(docker inspect --format='{{.Config.Image}}' "$container" 2>/dev/null)
              if [ -n "$image" ]; then
                docker pull "$image"
              fi

              # Recreate container using service name
              cd "$(dirname "$compose_file")"
              docker compose -f "$(basename "$compose_file")" up -d --force-recreate "$service_name" || true
              cd - > /dev/null

              updated="${updated}${container}, "
            else
              echo "Warning: No compose file mapped for $container"
            fi
          done

          echo "Updated containers: ${updated%, }"

      - name: Wait for services to stabilize
        run: sleep 15

      - name: Notify Home Assistant of completion
        continue-on-error: true
        env:
          HA_URL: ${{ vars.HA_URL }}
          HA_TOKEN: ${{ secrets.HA_LONG_LIVED_TOKEN }}
          CONTAINERS: ${{ github.event.inputs.containers }}
        run: |
          # Retry up to 3 times with 10 second delay
          for i in 1 2 3; do
            if curl -s --fail --max-time 30 -X POST \
              -H "Authorization: Bearer ${HA_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{
                \"event_type\": \"docker_updates_applied\",
                \"event_data\": {
                  \"host\": \"docker-critical\",
                  \"containers\": \"${CONTAINERS}\"
                }
              }" \
              "${HA_URL}/api/events/docker_updates_applied"; then
              echo "Successfully notified Home Assistant"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
          echo "Failed to notify Home Assistant after 3 attempts"
