name: Check Updates - Docker NonCritical

on:
  schedule:
    # Run daily at 4pm Central (22:00 UTC in winter, 21:00 UTC in summer)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: hac-noncritical

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          ref: main

      - name: Check for container updates
        id: check
        env:
          # Containers to check on docker-noncritical
          CONTAINERS: "plex sonarr radarr lidarr readarr prowlarr overseerr qbittorrent sabnzbd traefik flaresolverr"
        run: |
          set +e  # Don't exit on errors - we handle them ourselves
          chmod +x ./scripts/check-docker-updates.sh

          echo "=== Using commit: $(git log -1 --oneline) ==="

          # Collect update objects into an array
          updates_arr=()
          for container in $CONTAINERS; do
            if docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
              echo "========================================"
              echo "Checking container: $container"
              echo "========================================"
              # Run once and capture both stderr (debug) and stdout (result)
              output=$(./scripts/check-docker-updates.sh "$container" 2>&1 || true)
              echo "$output"
              # Extract just the JSON line (starts with {) for the result
              result=$(echo "$output" | grep '^\{' | head -1 || true)
              # Script outputs a JSON object if update available, empty if not
              if [ -n "$result" ] && [[ "$result" == "{"* ]]; then
                updates_arr+=("$result")
                echo "  -> Update available"
              else
                echo "  -> No update (or error)"
              fi
            else
              echo "Container not running: $container"
            fi
          done

          # Build JSON array from collected objects
          if [ ${#updates_arr[@]} -eq 0 ]; then
            updates="[]"
          else
            updates="[$(IFS=,; echo "${updates_arr[*]}")]"
          fi

          echo "updates=$updates" >> $GITHUB_OUTPUT
          echo "Found updates: $updates"

      - name: Send notification to Home Assistant
        if: steps.check.outputs.updates != '[]'
        env:
          HA_URL: ${{ vars.HA_URL }}
          HA_TOKEN: ${{ secrets.HA_LONG_LIVED_TOKEN }}
        run: |
          # Get updates from output (using heredoc to handle special chars)
          UPDATES='${{ steps.check.outputs.updates }}'

          echo "DEBUG: UPDATES=$UPDATES"

          # Parse updates using jq for reliable JSON handling
          count=$(echo "$UPDATES" | jq 'length')
          containers=$(echo "$UPDATES" | jq -r '[.[].container] | join(", ")')

          echo "DEBUG: count=$count containers=$containers"

          # Build JSON payload properly with jq
          # Note: HA /api/events/{event_type} expects event data directly, not wrapped
          payload=$(jq -n \
            --arg host "hac-noncritical" \
            --argjson count "$count" \
            --arg containers "$containers" \
            --argjson updates "$UPDATES" \
            '{
              host: $host,
              count: $count,
              containers: $containers,
              updates: $updates
            }')

          echo "DEBUG: Sending payload:"
          echo "$payload" | jq .

          # Fire an event to Home Assistant
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer ${HA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${HA_URL}/api/events/docker_updates_available")

          http_code=$(echo "$response" | tail -1)
          body=$(echo "$response" | head -n -1)

          echo "DEBUG: HTTP $http_code - Response: $body"

          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "Notification sent to Home Assistant successfully"
          else
            echo "ERROR: Failed to send notification (HTTP $http_code)"
            exit 1
          fi
