name: Check Updates - Docker NonCritical

on:
  schedule:
    # Run daily at 4pm Central (22:00 UTC in winter, 21:00 UTC in summer)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: docker-noncritical

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          ref: main

      - name: Check for container updates
        id: check
        env:
          # Containers to check on docker-noncritical
          CONTAINERS: "plex sonarr radarr lidarr readarr prowlarr overseerr qbittorrent sabnzbd traefik flaresolverr"
        run: |
          chmod +x ./scripts/check-docker-updates.sh

          # Collect update objects into an array
          updates_arr=()
          for container in $CONTAINERS; do
            if docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
              echo "Checking container: $container"
              result=$(./scripts/check-docker-updates.sh "$container" 2>/dev/null)
              # Script outputs a JSON object if update available, empty if not
              if [ -n "$result" ] && [[ "$result" == "{"* ]]; then
                updates_arr+=("$result")
                echo "  -> Update available"
              else
                echo "  -> No update (or error)"
              fi
            else
              echo "Container not running: $container"
            fi
          done

          # Build JSON array from collected objects
          if [ ${#updates_arr[@]} -eq 0 ]; then
            updates="[]"
          else
            updates="[$(IFS=,; echo "${updates_arr[*]}")]"
          fi

          echo "updates=$updates" >> $GITHUB_OUTPUT
          echo "Found updates: $updates"

      - name: Send notification to Home Assistant
        if: steps.check.outputs.updates != '[]'
        env:
          HA_URL: ${{ vars.HA_URL }}
          HA_TOKEN: ${{ secrets.HA_LONG_LIVED_TOKEN }}
          UPDATES: ${{ steps.check.outputs.updates }}
        run: |
          # Parse updates and create message
          count=$(echo "$UPDATES" | grep -o '"container"' | wc -l)
          containers=$(echo "$UPDATES" | grep -o '"container":"[^"]*"' | cut -d'"' -f4 | tr '\n' ', ' | sed 's/,$//')

          # Fire an event to Home Assistant
          curl -s -X POST \
            -H "Authorization: Bearer ${HA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"event_type\": \"docker_updates_available\",
              \"event_data\": {
                \"host\": \"docker-noncritical\",
                \"count\": ${count},
                \"containers\": \"${containers}\",
                \"updates\": ${UPDATES}
              }
            }" \
            "${HA_URL}/api/events/docker_updates_available"

          echo "Notification sent to Home Assistant"
