name: Deploy Govee2MQTT

on:
  push:
    branches:
      - main
    paths:
      - "Docker-Critical/Home/Govee2MQTT/**"
      - ".forgejo/workflows/deploy-govee2mqtt.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker-critical-linux-x64
    defaults:
      run:
        shell: sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Govee2MQTT
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CERTRESOLVER: ${{ vars.CERTRESOLVER }}
          GOVEE_API_KEY: ${{ secrets.GOVEE_API_KEY }}
          GOVEE_DEVICES: ${{ vars.GOVEE_DEVICES }}
          TZ: ${{ vars.TZ }}
        run: |
          defined_image=$(grep -m1 'image:' Docker-Critical/Home/Govee2MQTT/govee2mqtt.yml | awk '{print $2}')
          running_image=$(docker inspect -f '{{.Config.Image}}' govee2mqtt 2>/dev/null || echo "none")
          checksum=$(sha256sum Docker-Critical/Home/Govee2MQTT/govee2mqtt.yml | awk '{print $1}')
          old=$(sudo cat /srv/govee2mqtt/.govee2mqtt_checksum 2>/dev/null || echo "")

          if [ "$defined_image" != "$running_image" ] || [ "$checksum" != "$old" ]; then
            echo "Redeploying Govee2MQTT..."
            sudo mkdir -p /srv/govee2mqtt
            sudo cp Docker-Critical/Home/Govee2MQTT/govee2mqtt.yml /srv/govee2mqtt/
            sudo chmod 644 /srv/govee2mqtt/govee2mqtt.yml

            cd /srv/govee2mqtt
            env DOMAIN_NAME=$DOMAIN_NAME \
              CERTRESOLVER=${CERTRESOLVER:-cloudflare} \
              GOVEE_API_KEY=$GOVEE_API_KEY \
              GOVEE_DEVICES=${GOVEE_DEVICES:-} \
              TZ=${TZ:-America/Chicago} \
              docker compose -p govee2mqtt -f govee2mqtt.yml up -d --force-recreate

            sudo sh -c "echo '$checksum' > /srv/govee2mqtt/.govee2mqtt_checksum"
          else
            echo "No changes detected; skipping redeploy"
          fi
