name: Deploy Omada Controller

on:
  push:
    branches:
      - main
    paths:
      - "Docker-Critical/Networking/Omada/omada.yml"
      - ".forgejo/workflows/deploy-omada.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker-critical-linux-x64
    defaults:
      run:
        shell: sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify compose file exists
        run: ls -l "./Docker-Critical/Networking/Omada/omada.yml"

      - name: Deploy Omada Controller
        working-directory: "./Docker-Critical/Networking/Omada"
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CERTRESOLVER: ${{ vars.CERTRESOLVER }}
        run: |
          # Validate required vars
          for var in DOMAIN_NAME; do
            eval val=\$$var
            if [ -z "$val" ]; then
              echo "Missing required variable: $var" >&2
              exit 1
            fi
          done

          defined_image=$(grep -m1 'image:' omada.yml | awk '{print $2}')
          running_image=$(docker inspect -f '{{.Config.Image}}' omada-controller 2>/dev/null || echo "none")
          checksum=$(sha256sum omada.yml | awk '{print $1}')
          old=$(sudo cat /srv/omada/.omada_checksum 2>/dev/null || echo "")

          if [ "$defined_image" != "$running_image" ] || [ "$checksum" != "$old" ]; then
            echo "Redeploying Omada Controller..."
            sudo mkdir -p /srv/omada
            sudo cp omada.yml /srv/omada/
            cd /srv/omada
            docker compose -p omada down --remove-orphans || true
            docker compose -p omada -f omada.yml up -d --force-recreate
            sudo sh -c "echo '$checksum' > /srv/omada/.omada_checksum"
          fi
