name: Deploy Wazuh

on:
  push:
    branches:
      - main
    paths:
      - "Docker-NonCritical/Security/**"
      - ".forgejo/workflows/deploy-wazuh.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker-noncritical

    defaults:
      run:
        shell: sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Wazuh compose file exists
        run: |
          ls -l "./Docker-NonCritical/Security/security.yaml"

      - name: Compare image and config
        working-directory: "./Docker-NonCritical/Security"
        env:
          TZ: ${{ vars.TZ }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CERTRESOLVER: ${{ vars.CERTRESOLVER }}
          WAZUH_VERSION: ${{ vars.WAZUH_VERSION }}
          WAZUH_INDEXER_USERNAME: ${{ vars.WAZUH_INDEXER_USERNAME }}
          WAZUH_API_USERNAME: ${{ vars.WAZUH_API_USERNAME }}
          WAZUH_INDEXER_PASSWORD: ${{ secrets.WAZUH_INDEXER_PASSWORD }}
          WAZUH_API_PASSWORD: ${{ secrets.WAZUH_API_PASSWORD }}
        run: |
          # Extract defined image versions
          defined_indexer=$(grep -A2 'wazuh.indexer:' security.yaml | grep 'image:' | awk '{print $2}')
          defined_manager=$(grep -A2 'wazuh.manager:' security.yaml | grep 'image:' | awk '{print $2}')
          defined_dashboard=$(grep -A2 'wazuh.dashboard:' security.yaml | grep 'image:' | awk '{print $2}')

          # Extract running images
          running_indexer=$(docker inspect -f '{{.Config.Image}}' wazuh-indexer 2>/dev/null || echo "none")
          running_manager=$(docker inspect -f '{{.Config.Image}}' wazuh-manager 2>/dev/null || echo "none")
          running_dashboard=$(docker inspect -f '{{.Config.Image}}' wazuh-dashboard 2>/dev/null || echo "none")

          # Compute checksum of compose file + config files
          checksum=$(cat security.yaml indexer-config/opensearch.yml indexer-config/ism-policy.json indexer-config/apply-ism-policy.sh dashboard-config/opensearch_dashboards.yml | sha256sum | awk '{print $1}')
          old=$(cat .wazuh_checksum 2>/dev/null || echo "")

          echo "Indexer - Defined: $defined_indexer | Running: $running_indexer"
          echo "Manager - Defined: $defined_manager | Running: $running_manager"
          echo "Dashboard - Defined: $defined_dashboard | Running: $running_dashboard"
          echo "Checksum: $checksum vs $old"

          if [ "$defined_indexer" != "$running_indexer" ] || \
             [ "$defined_manager" != "$running_manager" ] || \
             [ "$defined_dashboard" != "$running_dashboard" ] || \
             [ "$checksum" != "$old" ]; then
            echo "Redeploying Wazuh stack"

            # Deploy
            TZ=$TZ DOMAIN_NAME=$DOMAIN_NAME CERTRESOLVER=$CERTRESOLVER \
              WAZUH_VERSION=$WAZUH_VERSION \
              WAZUH_INDEXER_USERNAME=$WAZUH_INDEXER_USERNAME \
              WAZUH_API_USERNAME=$WAZUH_API_USERNAME \
              WAZUH_INDEXER_PASSWORD=$WAZUH_INDEXER_PASSWORD \
              WAZUH_API_PASSWORD=$WAZUH_API_PASSWORD \
              docker compose -p wazuh -f security.yaml down --remove-orphans --volumes || true

            # Also remove any leftover Docker-managed volumes from previous config
            docker volume rm wazuh_wazuh-dashboard-config wazuh_wazuh-dashboard-custom 2>/dev/null || true

            # Wait a moment for cleanup
            sleep 5

            # Clear stale manager state so the entrypoint re-initializes cleanly.
            # Preserves queue (agent keys) but wipes config/state dirs that may
            # be corrupt from previous failed deployments.
            rm -rf /srv/wazuh/manager/etc/*
            rm -rf /srv/wazuh/manager/logs/*
            rm -rf /srv/wazuh/filebeat/etc/*
            rm -rf /srv/wazuh/filebeat/var/*
            rm -rf /srv/wazuh/indexer-data/*

            # Create all bind-mounted directories with correct ownership
            YEAR=$(date +%Y)

            # Indexer data
            mkdir -p /srv/wazuh/indexer-data
            chown -R 1000:1000 /srv/wazuh/indexer-data

            # Manager directories (all bind mounts from compose)
            mkdir -p /srv/wazuh/manager/api-configuration
            mkdir -p /srv/wazuh/manager/etc
            mkdir -p /srv/wazuh/manager/queue
            mkdir -p /srv/wazuh/manager/var-multigroups
            mkdir -p /srv/wazuh/manager/integrations
            mkdir -p /srv/wazuh/manager/active-response
            mkdir -p /srv/wazuh/manager/agentless
            mkdir -p /srv/wazuh/manager/wodles
            mkdir -p /srv/wazuh/filebeat/etc
            mkdir -p /srv/wazuh/filebeat/var

            # Manager logs — analysisd needs these year-based subdirectories
            mkdir -p /srv/wazuh/manager/logs/alerts/$YEAR
            mkdir -p /srv/wazuh/manager/logs/archives/$YEAR
            mkdir -p /srv/wazuh/manager/logs/firewall/$YEAR
            mkdir -p /srv/wazuh/manager/logs/cluster
            chown -R 1000:1000 /srv/wazuh/manager

            # NFS archive target
            mkdir -p /mnt/data/wazuh/archives

            # Dashboard directories
            mkdir -p /srv/wazuh/dashboard/config
            mkdir -p /srv/wazuh/dashboard/custom

            # Pre-create wazuh.yml so dashboard connects to API with run_as: false
            printf 'hosts:\n  - default:\n      url: https://wazuh.manager\n      port: 55000\n      username: %s\n      password: %s\n      run_as: false\n' \
              "$WAZUH_API_USERNAME" "$WAZUH_API_PASSWORD" \
              > /srv/wazuh/dashboard/config/wazuh.yml

            TZ=$TZ DOMAIN_NAME=$DOMAIN_NAME CERTRESOLVER=$CERTRESOLVER \
              WAZUH_VERSION=$WAZUH_VERSION \
              WAZUH_INDEXER_USERNAME=$WAZUH_INDEXER_USERNAME \
              WAZUH_API_USERNAME=$WAZUH_API_USERNAME \
              WAZUH_INDEXER_PASSWORD=$WAZUH_INDEXER_PASSWORD \
              WAZUH_API_PASSWORD=$WAZUH_API_PASSWORD \
              docker compose -p wazuh -f security.yaml up -d --force-recreate

            # Save checksum
            echo "$checksum" > .wazuh_checksum

            echo "✅ Wazuh stack deployed successfully"
            echo "🌐 Access at: https://wazuh.$DOMAIN_NAME"
          else
            echo "No redeploy needed"
          fi

      - name: Verify deployment
        run: |
          echo "Waiting for services to initialize..."
          sleep 30

          # Check if containers are running
          docker ps | grep wazuh-indexer && echo "✅ Indexer running" || echo "❌ Indexer not running"
          docker ps | grep wazuh-manager && echo "✅ Manager running" || echo "❌ Manager not running"
          docker ps | grep wazuh-dashboard && echo "✅ Dashboard running" || echo "❌ Dashboard not running"

          # Dump full manager service status for diagnostics
          echo ""
          echo "Full wazuh-control status:"
          docker exec wazuh-manager /var/ossec/bin/wazuh-control status 2>/dev/null || echo "(wazuh-control not available yet)"

          echo ""
          echo "Checking ossec.conf exists:"
          docker exec wazuh-manager ls -la /var/ossec/etc/ossec.conf 2>/dev/null || echo "❌ ossec.conf missing!"

          # Verify analysisd is running inside the manager (critical service)
          echo ""
          echo "Checking wazuh-analysisd..."
          for i in 1 2 3 4 5 6; do
            if docker exec wazuh-manager /var/ossec/bin/wazuh-control status 2>/dev/null | grep -q "wazuh-analysisd is running"; then
              echo "✅ wazuh-analysisd is running"
              break
            fi
            if [ "$i" -eq 6 ]; then
              echo "❌ wazuh-analysisd failed to start after 60s"
              echo "Manager logs (last 30 lines):"
              docker exec wazuh-manager tail -30 /var/ossec/logs/ossec.log 2>/dev/null || true
              exit 1
            fi
            echo "  Attempt $i/6 — analysisd not ready yet, waiting 10s..."
            sleep 10
          done

      - name: Notify Home Assistant
        if: always()
        env:
          HA_URL: ${{ vars.HA_URL }}
          HA_TOKEN: ${{ secrets.HA_LONG_LIVED_TOKEN }}
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            MESSAGE="✅ Wazuh deployment successful"
            SEVERITY="info"
          else
            MESSAGE="❌ Wazuh deployment failed"
            SEVERITY="error"
          fi

          curl -X POST "$HA_URL/api/services/notify/persistent_notification" \
            -H "Authorization: Bearer $HA_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"message\": \"$MESSAGE\",
              \"title\": \"Wazuh Deployment\",
              \"data\": {
                \"tag\": \"wazuh-deployment\"
              }
            }" || echo "Failed to notify Home Assistant"
