name: Deploy Docker Socket Proxy - Critical

on:
  push:
    branches:
      - main
    paths:
      - "Docker-Critical/Tools/DockerSocketProxy/**"
      - ".forgejo/workflows/deploy-docker-socket-proxy-critical.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker-critical:host

    defaults:
      run:
        shell: sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Docker Socket Proxy
        working-directory: "./Docker-Critical/Tools/DockerSocketProxy"
        env:
          TZ: ${{ vars.TZ }}
        run: |
          docker compose -p docker-socket-proxy -f docker-socket-proxy.yml up -d --force-recreate
