services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    networks:
      - mediaproxy
    environment:
      - TZ=${TZ:-America/Chicago}
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME:-immich}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE:-immich}
      - REDIS_HOSTNAME=immich-valkey
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.rule=Host(`media.${DOMAIN_NAME}`)
      - traefik.http.routers.immich.service=immich
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.immich.tls.domains[0].main=media.${DOMAIN_NAME}
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=media"
      - "ha.compose-file=Docker-NonCritical/Media/Immich/immich.yml"
      - "ha.service-name=immich"
    volumes:
      - /mnt/data/family/upload:/usr/src/app/upload
      - /mnt/data/family/external:/usr/src/app/external
    depends_on:
      immich-valkey:
        condition: service_started
      immich-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2283/api/server/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    restart: unless-stopped
    networks:
      - mediaproxy
    environment:
      - TZ=${TZ:-America/Chicago}
    volumes:
      - /srv/immich/model-cache:/cache
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:3003')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  immich-valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: immich-valkey
    restart: unless-stopped
    networks:
      - mediaproxy
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    networks:
      - mediaproxy
    environment:
      - POSTGRES_USER=${IMMICH_DB_USERNAME:-immich}
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_DB=${IMMICH_DB_DATABASE:-immich}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - /srv/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${IMMICH_DB_DATABASE:-immich} -U ${IMMICH_DB_USERNAME:-immich}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mediaproxy:
    external: true
