services:
  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    restart: unless-stopped
    # Use homeproxy network for Traefik routing with other home services
    networks:
      - homeproxy
    ports:
      - "8095:8095"
      - "8097:8097"
    environment:
      - TZ=${TZ:-America/Chicago}
      - LOG_LEVEL=info
    # Required privileges for mounting SMB/NFS shares and device discovery
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - /srv/music-assistant/data:/data
      # Mount media library for local file access (optional, adjust path as needed)
      - /mnt/data/media/music:/media/music:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.musicassistant.entrypoints=websecure
      - traefik.http.routers.musicassistant.rule=Host(`music.${DOMAIN_NAME}`)
      - traefik.http.routers.musicassistant.service=musicassistant
      - traefik.http.services.musicassistant.loadbalancer.server.port=8095
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=home"
      - "ha.compose-file=Docker-Critical/Home/MusicAssistant/musicassistant.yml"
      - "ha.service-name=music-assistant"
    healthcheck:
      # Use GET request to a more appropriate endpoint and suppress warnings
      test: ["CMD-SHELL", "wget --quiet --tries=1 --output-document=/dev/null http://localhost:8095/api/server/info 2>/dev/null || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s

networks:
  homeproxy:
    external: true
