services:
  # IBM ContextForge MCP Gateway - Central gateway for all MCP servers
  mcp-gateway:
    image: ghcr.io/ibm/mcp-context-forge:latest
    container_name: mcp-gateway
    restart: unless-stopped
    networks:
      - mcpnet
      - aiproxy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${MCP_DB_USERNAME:-mcpuser}:${MCP_DB_PASSWORD}@mcp-postgres:5432/mcpgateway
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - ADMIN_UI_ENABLED=true
    depends_on:
      mcp-postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /srv/mcp-gateway/config:/app/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.mcpgateway.entrypoints=websecure
      - traefik.http.routers.mcpgateway.rule=Host(`mcp.${DOMAIN_NAME}`)
      - traefik.http.routers.mcpgateway.service=mcpgateway
      - traefik.http.services.mcpgateway.loadbalancer.server.port=3000
      - traefik.http.routers.mcpgateway.tls.certresolver=${CERTRESOLVER}
      - traefik.http.routers.mcpgateway.tls.domains[0].main=mcp.${DOMAIN_NAME}
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=mcp-gateway"

  # PostgreSQL for MCP Gateway
  mcp-postgres:
    image: postgres:15
    container_name: mcp-postgres
    restart: unless-stopped
    networks:
      - mcpnet
    environment:
      - POSTGRES_DB=mcpgateway
      - POSTGRES_USER=${MCP_DB_USERNAME:-mcpuser}
      - POSTGRES_PASSWORD=${MCP_DB_PASSWORD}
    volumes:
      - /srv/mcp-gateway/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mcpgateway -U ${MCP_DB_USERNAME:-mcpuser}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=mcp-postgres"

  # Redis for MCP Gateway caching and federation
  redis:
    image: redis:alpine
    container_name: mcp-redis
    restart: unless-stopped
    networks:
      - mcpnet
    volumes:
      - /srv/mcp-gateway/redis:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=redis"

  # Home Assistant MCP Server
  homeassistant-mcp:
    image: ghcr.io/jango-blockchained/advanced-homeassistant-mcp:latest
    container_name: mcp-homeassistant
    restart: unless-stopped
    networks:
      - mcpnet
    environment:
      - HASS_HOST=${HOMEASSISTANT_URL}
      - HASS_TOKEN=${HA_LONG_LIVED_TOKEN}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=homeassistant-mcp"

  # OPNsense MCP Server
  opnsense-mcp:
    image: node:20-alpine
    container_name: mcp-opnsense
    restart: unless-stopped
    networks:
      - mcpnet
    working_dir: /app
    command: npx -y @pixelworlds/opnsense-mcp-server
    environment:
      - OPNSENSE_URL=${OPNSENSE_URL}
      - OPNSENSE_API_KEY=${OPNSENSE_API_KEY}
      - OPNSENSE_API_SECRET=${OPNSENSE_API_SECRET}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=opnsense-mcp"

  # NetBox MCP Server
  netbox-mcp:
    image: node:20-alpine
    container_name: mcp-netbox
    restart: unless-stopped
    networks:
      - mcpnet
    working_dir: /app
    command: npx -y @netboxlabs/netbox-mcp-server
    environment:
      - NETBOX_URL=${NETBOX_URL}
      - NETBOX_API_TOKEN=${NETBOX_API_TOKEN}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=netbox-mcp"

  # n8n MCP Server (custom implementation)
  n8n-mcp:
    build:
      context: ./mcp-servers/n8n
      dockerfile: Dockerfile
    container_name: mcp-n8n
    restart: unless-stopped
    networks:
      - mcpnet
    environment:
      - N8N_URL=${N8N_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=n8n-mcp"

  # TP-Link Omada MCP Server (custom implementation)
  omada-mcp:
    build:
      context: ./mcp-servers/omada
      dockerfile: Dockerfile
    container_name: mcp-omada
    restart: unless-stopped
    networks:
      - mcpnet
    environment:
      - OMADA_URL=${OMADA_URL}
      - OMADA_USERNAME=${OMADA_USERNAME}
      - OMADA_PASSWORD=${OMADA_PASSWORD}
      - OMADA_SITE_ID=${OMADA_SITE_ID}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=omada-mcp"

  # Vikunja MCP Server (task management)
  vikunja-mcp:
    image: node:20-alpine
    container_name: mcp-vikunja
    restart: unless-stopped
    networks:
      - mcpnet
    working_dir: /app
    command: npx -y @democratize-technology/vikunja-mcp
    environment:
      - VIKUNJA_URL=${VIKUNJA_URL}
      - VIKUNJA_API_TOKEN=${VIKUNJA_API_TOKEN}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=vikunja-mcp"

  # HomeBox MCP Server (custom implementation)
  homebox-mcp:
    build:
      context: ./mcp-servers/homebox
      dockerfile: Dockerfile
    container_name: mcp-homebox
    restart: unless-stopped
    networks:
      - mcpnet
    environment:
      - HOMEBOX_URL=${HOMEBOX_URL}
      - HOMEBOX_EMAIL=${HOMEBOX_EMAIL}
      - HOMEBOX_PASSWORD=${HOMEBOX_PASSWORD}
      - MCP_TRANSPORT=sse
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - "ha.monitor=true"
      - "ha.category=tools"
      - "ha.compose-file=Docker-NonCritical/Tools/MCPGateway/mcpgateway.yml"
      - "ha.service-name=homebox-mcp"

networks:
  mcpnet:
    driver: bridge
  aiproxy:
    external: true
