services:
  rtl_433:
    image: hertzg/rtl_433:latest
    container_name: rtl_433
    restart: unless-stopped
    networks:
      - homeproxy
    environment:
      - TZ=${TZ:-America/Chicago}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /srv/rtl-sdr/config:/config
      - /srv/rtl-sdr/data:/data
    command: >
      -c /config/rtl_433.conf
      -F mqtt://${MQTT_HOST:-homeassistant-mqtt}:${MQTT_PORT:-1883},user=${MQTT_USER:-mqtt},pass=${MQTT_PASSWORD:-mqtt},retain=1,devices=rtl_433[/model][/id]
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  homeproxy:
    external: true
