services:
  web:
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    volumes:
      - ${KARAKEEP_DATA:-/opt/Docker-Critical/KaraKeep/data}:/data
    networks:
      - toolsproxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kara.entrypoints=websecure
      - traefik.http.routers.kara.rule=Host(`kara.${DOMAIN_NAME}`)
      - traefik.http.routers.kara.service=kara
      - traefik.http.services.kara.loadbalancer.server.port=3000
      - traefik.http.routers.kara.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.kara.tls.domains[0].main=kara.${DOMAIN_NAME}
      - com.centurylinklabs.watchtower.enable=true
    environment:
      MEILI_ADDR: ${MEILI_ADDR:-http://localhost:7700}
      BROWSER_WEB_URL: ${BROWSER_WEB_URL:-http://localhost:9222}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://kara.${DOMAIN_NAME}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-https://ollama.${DOMAIN_NAME}}
      INFERENCE_TEXT_MODEL: ${INFERENCE_TEXT_MODEL:-gemma3:4b}
      INFERENCE_IMAGE_MODEL: ${INFERENCE_IMAGE_MODEL:-gemma3:4b}
      INFERENCE_CONTEXT_LENGTH: ${INFERENCE_CONTEXT_LENGTH:-8192}
      CRAWLER_VIDEO_DOWNLOAD: ${CRAWLER_VIDEO_DOWNLOAD:-true}
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    network_mode: service:web
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: QamDHWGzdjY8f1aWVAaommshA4juOVwrZ87UDyVhmcJAiYXPW9x9qUUk8IrrwrWq
      MEILI_NO_ANALYTICS: "true"
      MEILI_ENV: production
    network_mode: service:web
    volumes:
      - meilisearch:/meili_data
networks:
  toolsproxy:
    external: true
volumes:
  meilisearch:
