services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: unless-stopped
    networks:
      - toolsproxy
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
    ports:
      - "8088:8088" # HTTP portal
      - "8043:8043" # HTTPS portal (also via Traefik)
      - "8843:8843" # HTTPS guest portal
      - "29810:29810/udp" # EAP discovery
      - "29811:29811" # Manager v1 port
      - "29812:29812" # Manager v2 port
      - "29813:29813" # Port for adopt and upgrade
      - "29814:29814" # Port for manager/device discovery
    labels:
      - traefik.enable=true
      - traefik.http.routers.omada.entrypoints=websecure
      - traefik.http.routers.omada.rule=Host(`omada.${DOMAIN_NAME}`)
      - traefik.http.routers.omada.service=omada
      - traefik.http.routers.omada.tls=true
      - traefik.http.services.omada.loadbalancer.server.port=8043
      - traefik.http.services.omada.loadbalancer.server.scheme=https
      - traefik.http.services.omada.loadbalancer.serversTransport=omada-transport
      - traefik.http.serversTransports.omada-transport.insecureSkipVerify=true
      - traefik.http.routers.omada.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.omada.tls.domains[0].main=omada.${DOMAIN_NAME}
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /srv/omada/data:/opt/tplink/EAPController/data
      - /mnt/hdd/logs/omada:/opt/tplink/EAPController/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8043"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  toolsproxy:
    external: true
