networks:
  toolsproxy:
    external: true
    name: toolsproxy

services:
  kiwix:
    image: kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    networks:
      - toolsproxy
    command: /data/*.zim
    volumes:
      - /mnt/hdd/kiwix:/data:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.kiwix.entrypoints=websecure
      - traefik.http.routers.kiwix.rule=Host(`wikipedia.${DOMAIN_NAME}`)
      - traefik.http.routers.kiwix.service=kiwix
      - traefik.http.routers.kiwix.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.kiwix.tls.domains[0].main=wikipedia.${DOMAIN_NAME}
      - traefik.http.services.kiwix.loadbalancer.server.port=8080
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=tools
      - ha.compose-file=Docker-Critical/Tools/Kiwix/kiwix.yml
      - ha.service-name=kiwix
      # Auto-update
      - com.centurylinklabs.watchtower.enable=true
