services:
  dispatcharr:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    restart: unless-stopped
    networks:
      - mediaproxy
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    labels:
      - traefik.enable=true
      - traefik.http.routers.dispatcharr.entrypoints=websecure
      - traefik.http.routers.dispatcharr.rule=Host(`dispatcharr.${DOMAIN_NAME}`)
      - traefik.http.routers.dispatcharr.service=dispatcharr
      - traefik.http.services.dispatcharr.loadbalancer.server.port=9191
      - traefik.http.routers.dispatcharr.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.dispatcharr.tls.domains[0].main=dispatcharr.${DOMAIN_NAME}
      - com.centurylinklabs.watchtower.enable=true
      - "ha.monitor=true"
      - "ha.category=media"
      - "ha.compose-file=Docker-NonCritical/Media/Dispatcharr/dispatcharr.yml"
      - "ha.service-name=dispatcharr"
    volumes:
      - /srv/dispatcharr/data:/data
      # Process Priority Configuration (Optional)
      # Lower values = higher priority. Range: -20 (highest) to 19 (lowest)
      # Negative values require cap_add: SYS_NICE (uncomment below)
      #- UWSGI_NICE_LEVEL=-5   # uWSGI/FFmpeg/Streaming (default: 0, recommended: -5 for high priority)
      #- CELERY_NICE_LEVEL=5   # Celery/EPG/Background tasks (default: 5, low priority)
    #
    # Uncomment to enable high priority for streaming (required if UWSGI_NICE_LEVEL < 0)
    #cap_add:
    #  - SYS_NICE
    # Optional for hardware acceleration
    #devices:
    #  - /dev/dri:/dev/dri  # For Intel/AMD GPU acceleration (VA-API)
    # Uncomment the following lines for NVIDIA GPU support
    # NVidia GPU support (requires NVIDIA Container Toolkit)
    #deploy:
    #  resources:
    #      reservations:
    #          devices:
    #              - driver: nvidia
    #                count: all
    #                capabilities: [gpu]
networks:
  mediaproxy:
    external: true