services:
  influxdb:
    image: influxdb:2-alpine
    container_name: influxdb
    restart: unless-stopped
    networks:
      - toolsproxy
    environment:
      - INFLUXDB_DB=homeautomation
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=false
      - TZ=${TZ:-America/Chicago}
    volumes:
      - /srv/influxdb/data:/var/lib/influxdb2
      - /srv/influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    labels:
      - traefik.enable=true
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.rule=Host(`influx.${DOMAIN_NAME}`)
      - traefik.http.routers.influxdb.service=influxdb
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  toolsproxy:
    external: true
