services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - secproxy
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/linux
      - GID=${PGID:-568}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - /srv/crowdsec/config:/etc/crowdsec
      - /srv/crowdsec/data:/var/lib/crowdsec/data
      - /var/log:/var/log/host:ro
    labels:
      # Traefik routing
      - traefik.enable=true
      - traefik.http.routers.crowdsec.entrypoints=websecure
      - traefik.http.routers.crowdsec.rule=Host(`crowdsec.${DOMAIN_NAME}`)
      - traefik.http.routers.crowdsec.service=crowdsec
      - traefik.http.services.crowdsec.loadbalancer.server.port=8080
      - traefik.http.routers.crowdsec.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.crowdsec.tls.domains[0].main=crowdsec.${DOMAIN_NAME}
      - traefik.http.routers.crowdsec.middlewares=authelia@docker
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=security
      - ha.compose-file=Docker-NonCritical/Security/Crowdsec/crowdsec.yml
      - ha.service-name=crowdsec
    healthcheck:
      test: ["CMD", "cscli", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  secproxy:
    external: true
