networks:
  toolsproxy:
    external: true

services:
  speedtest:
    image: openspeedtest/latest:latest
    container_name: speedtest
    restart: unless-stopped

    labels:
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=tools
      - ha.compose-file=Docker-NonCritical/Tools/Speedtest/speedtest.yml
      - ha.service-name=speedtest
      # Traefik routing
      - traefik.enable=true
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${DOMAIN_NAME}`)
      - traefik.http.routers.speedtest.service=speedtest
      - traefik.http.services.speedtest.loadbalancer.server.port=3000
      - traefik.http.routers.speedtest.tls.certresolver=${CERTRESOLVER}

    networks:
      - toolsproxy
