services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    networks:
      - mediaproxy
    ports:
      - "9001:9001"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
      - TZ=${TZ:-America/Chicago}
      - DOCKER_HOST=tcp://docker-socket-proxy-noncritical:2375
    labels:
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=tools
      - ha.compose-file=Docker-NonCritical/Tools/PortainerAgent/portainer-agent.yml
      - ha.service-name=portainer-agent
      # Watchtower auto-updates
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mediaproxy:
    external: true
