services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - toolsproxy
    volumes:
      - /srv/portainer/data:/data
    environment:
      - TZ=${TZ:-America/Chicago}
    command: --host=tcp://docker-socket-proxy:2375
    labels:
      # Traefik routing
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.tls.certresolver=${CERTRESOLVER:-cloudflare}
      - traefik.http.routers.portainer.tls.domains[0].main=portainer.${DOMAIN_NAME}
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      # Authelia protection
      - traefik.http.routers.portainer.middlewares=authelia@docker
      # Watchtower auto-updates
      - com.centurylinklabs.watchtower.enable=true
      # Home Assistant monitoring
      - ha.monitor=true
      - ha.category=tools
      - ha.compose-file=Docker-Critical/Tools/Portainer/portainer.yml
      - ha.service-name=portainer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  toolsproxy:
    external: true
