services:
  govee2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    network_mode: host
    environment:
      - GOVEE_EMAIL=${GOVEE_EMAIL}
      - GOVEE_PASSWORD=${GOVEE_PASSWORD}
      - GOVEE_API_KEY=${GOVEE_API_KEY}
      - GOVEE_MQTT_HOST=localhost
      - GOVEE_MQTT_PORT=1883
      - GOVEE_MQTT_USER=${GOVEE_MQTT_USER:-}
      - GOVEE_MQTT_PASSWORD=${GOVEE_MQTT_PASSWORD:-}
      - GOVEE_TEMPERATURE_SCALE=${GOVEE_TEMPERATURE_SCALE:-C}
      - RUST_LOG_STYLE=always
      - RUST_LOG=${RUST_LOG:-govee=info}
      - TZ=${TZ:-America/Chicago}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /srv/govee2mqtt/data:/data
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - homeproxy
    environment:
      - TZ=${TZ:-America/Chicago}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /srv/govee2mqtt/mosquitto/config:/mosquitto/config
      - /srv/govee2mqtt/mosquitto/data:/mosquitto/data
      - /srv/govee2mqtt/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"

networks:
  homeproxy:
    external: true
