networks:
  toolsproxy:
    external: True
    name: gitproxy
services:
  it-tools:
    container_name: it-tools
    image: ghcr.io/corentinth/it-tools:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.ittools.entrypoints=websecure
      - traefik.http.routers.ittools.rule=Host(`it-tools.u-acres.com`)
      - traefik.http.routers.ittools.service=ittools
      - traefik.http.services.ittools.loadbalancer.server.port=80
    networks:
      - toolsproxy
    restart: unless-stopped
  stirling-pdf:
    container_name: stirling-pdf
    environment:
      - DOCKER_ENABLE_SECURITY=false
    image: frooodle/s-pdf:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.pdf.entrypoints=websecure
      - traefik.http.routers.pdf.rule=Host(`pdf.u-acres.com`)
      - traefik.http.routers.pdf.service=pdf
      - traefik.http.services.pdf.loadbalancer.server.port=8080
    networks:
      - toolsproxy
    restart: unless-stopped
    volumes:
      - /mnt/Apps/pdf/stirling-pdf:/configs
  searx:
    image: searxng/searxng:latest
    container_name: searx
    restart: always
    volumes:
        - /mnt/Apps/searx:/etc/searx
    networks:
      - toolsproxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.searx.entrypoints=websecure
      - traefik.http.routers.searx.rule=Host(`search.u-acres.com`)
      - traefik.http.routers.searx.service=searx
      - traefik.http.services.searx.loadbalancer.server.port=8080
