services:
  norish:
    image: norishapp/norish:latest
    container_name: norish-app
    # user: "1000:1000"  # Match your host user's UID:GID (run `id` to check), only needed with bind mounts
    # The example uses named volume 'norish_data' which handles permissions automatically
    restart: always # Required for server restart functionality
    networks:
      - homeproxy
    user: "568:568"
    volumes:
      - /srv/norish/app/uploads:/app/uploads
    environment:
      # Core settings (required)
      AUTH_URL: https://norish.${DOMAIN_NAME}
      DATABASE_URL: postgres://postgres:${NORISH_DB_PASSWORD}@norish-db:5432/norish
      MASTER_KEY: ${NORISH_MASTER_KEY} # Secret
      CHROME_WS_ENDPOINT: ws://chrome-headless:3000
      REDIS_URL: redis://redis:6379

      # OPTIONAL
      # NEXT_PUBLIC_LOG_LEVEL: info       # trace, debug, info, warn, error, fatal (default: info in prod, debug in dev)
      # TRUSTED_ORIGINS:http://192.168.1.100:3000,https://norish.example.com  # Additional trusted origins, comma separated. Useful when behind a proxy or using multiple domains.
      # YT_DLP_BIN_DIR: # Custom folder path for `yt-dlp` (default: /app/bin)
      TRUSTED_ORIGINS: https://norish.${DOMAIN_NAME}
      # ─────────────────────────────────────────────────────────────────────────
      # FIRST USER SETUP
      # ─────────────────────────────────────────────────────────────────────────
      # On first startup, configure ONE auth provider below to create your admin account.
      # After first login, use Settings → Admin to configure additional providers,
      # AI settings, video parsing, and all other options.

      # Option 1= Password auth - basic auth with email/password
      # If not set defaults to disabled if OIDC or OAuth is configured.
      # Defaults to true if no other auth providers are configured.
      #PASSWORD_AUTH_ENABLED=false

      # Option 2: OIDC (Authentik, Keycloak, PocketID, etc.)
      OIDC_NAME: Authelia
      OIDC_ISSUER: https://authelia.${DOMAIN_NAME}
      OIDC_CLIENT_ID: norish
      OIDC_CLIENT_SECRET: ${NORISH_OIDC_CLIENT_SECRET} #secret
      OIDC_WELLKNOWN: https://authelia.${DOMAIN_NAME}/.well-known/openid-configuration
      # Wellknown is optional: By default the wellknown URL is derived from the issuer by appending /.well-known/openid-configuration

      # Option 3: GitHub OAuth (uncomment and remove OIDC above)
      # GITHUB_CLIENT_ID: <github-client-id>
      # GITHUB_CLIENT_SECRET: <github-client-secret>

      # Option 4: Google OAuth (uncomment and remove OIDC above)
      # GOOGLE_CLIENT_ID: <google-client-id>
      # GOOGLE_CLIENT_SECRET: <google-client-secret>
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.norish.rule=Host(`norish.${DOMAIN_NAME}`)"
      - "traefik.http.routers.norish.entrypoints=websecure"
      - "traefik.http.routers.norish.tls=true"
      - "traefik.http.routers.norish.tls.certresolver=${CERTRESOLVER:-cloudflare}"
      - "traefik.http.routers.norish.tls.domains[0].main=norish.${DOMAIN_NAME}"
      - "traefik.http.services.norish.loadbalancer.server.port=3000"
      - "traefik.http.routers.norish.middlewares=authelia@docker"
      - "ha.monitor=true"
      - "ha.category=home"
      - "ha.compose-file=Docker-Critical/Home/Cooking/norish.yml"
      - "ha.service-name=norish"

  db:
    image: postgres:17-alpine
    container_name: norish-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${NORISH_DB_PASSWORD}
      POSTGRES_DB: norish
    networks:
      - homeproxy
    volumes:
      - /srv/norish/postgres:/var/lib/postgresql/data
    labels:
      - "ha.monitor=true"
      - "ha.category=home"
      - "ha.compose-file=Docker-Critical/Home/Cooking/norish.yml"
      - "ha.service-name=db"

  # Chrome headless
  chrome-headless:
    image: zenika/alpine-chrome:latest
    container_name: chrome-headless
    restart: unless-stopped
    networks:
      - homeproxy
    command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=3000"
      - "--headless"
    labels:
      - "ha.monitor=true"
      - "ha.category=home"
      - "ha.compose-file=Docker-Critical/Home/Cooking/norish.yml"
      - "ha.service-name=chrome-headless"

  # Redis for real-time events and job queues
  redis:
    image: redis:8.4.0
    container_name: norish-redis
    restart: unless-stopped
    networks:
      - homeproxy
    volumes:
      - /srv/norish/redis_data:/data
    labels:
      - "ha.monitor=true"
      - "ha.category=home"
      - "ha.compose-file=Docker-Critical/Home/Cooking/norish.yml"
      - "ha.service-name=redis"
networks:
  homeproxy:
    external: true
